# Start an image with node base image.
# I'll be honest, I have no idea what the node:18-alpine image is
FROM node:18-alpine

# Sets the /app directory. This is the current app directory???
WORKDIR /app

# Copy contents of package.json files
#COPY package*.json ./
# TODO: docker files.

# Start the app with the serve command?
# RUN ["cd "]
#Services:
    #Web:
        #RUN
    # backend:
        #[...]

# Enter the program
# ENTRYPOINT["..."]